DROP DATABASE IF EXISTS pmb;

CREATE DATABASE pmb;

USE pmb;

DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS connection;
CREATE TABLE connection (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INTEGER NOT NULL,
    buddy_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (buddy_id) REFERENCES user (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS account;
CREATE TABLE account (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    balance FLOAT,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id)
);

DROP TABLE IF EXISTS transaction;
CREATE TABLE transaction (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    type VARCHAR(50) NOT NULL,
    amount FLOAT NOT NULL,
    description VARCHAR(250) NOT NULL,
    fees FLOAT NOT NULL,
    account_id INTEGER NOT NULL,
    connection_id INTEGER DEFAULT NULL
);